name: linecheck

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: tupe12334/linecheck@main
        with:
          version: "1.2.0"
